//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySelfieEntities : DbContext
    {
        public MySelfieEntities()
            : base("name=MySelfieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Packet> Packets { get; set; }
        public virtual DbSet<PhotoTweet> PhotoTweets { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
        public virtual DbSet<WorkerCommand> WorkerCommands { get; set; }
        public virtual DbSet<WorkerStatus> WorkerStatus { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<TwitterAccount> TwitterAccounts { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<WebLog> WebLogs { get; set; }
    }
}
