//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfie
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerCommand
    {
        public int WorkerCommandId { get; set; }
        public int WallId { get; set; }
        public string Command { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Wall Wall { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
