//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfie
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerStatus
    {
        public int WorkerStatusID { get; set; }
        public string Message { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Type { get; set; }
        public string Context { get; set; }
        public string UserName { get; set; }
        public string Header { get; set; }
        public string Status { get; set; }
    }
}
