//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfie.Scraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterAccount
    {
        public int TwitterAccountId { get; set; }
        public string TwitterUserName { get; set; }
        public string TwitterAppName { get; set; }
        public string ConsumerKey { get; set; }
        public string ConsumerSecret { get; set; }
        public string UserTokenKey { get; set; }
        public string UserTokenSecret { get; set; }
        public int TweetsCreatedToday { get; set; }
    }
}
